### ISSUE TITLE
Qwebirc not working

### ISSUE THREAD

**Issue by krdsx** [qwebirc/qwebirc#316]
2017-07-27T11:40:08+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.6.0 (/usr/bin/python 2.7.13) starting up.
2017-07-27T11:40:08+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-07-27T11:40:08+0200 [-] RootSite starting on 9090
2017-07-27T11:40:08+0200 [qwebirc.root.RootSite#info] Starting factory <qwebirc.root.RootSite instance at 0x7fec0eee1710>
2017-07-27T11:41:51+0200 [TimeoutHTTPChannel,0,66.249.93.73] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1752, in lineReceived
	    self.allContentReceived()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1845, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 766, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/home/user/qwebirc/qwebirc/engines/staticengine.py", line 33, in render
	    return static.File.render(self, request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 623, in render_GET
	    producer.start()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 702, in start
	    self.request.registerProducer(self, False)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 807, in registerProducer
	    self.channel.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2075, in registerProducer
	    return self.transport.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 233, in registerProducer
	    FileDescriptor.registerProducer(self, producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 112, in registerProducer
	    producer.resumeProducing()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 712, in resumeProducing
	    self.request.write(data)
	  File "/home/user/qwebirc/qwebirc/util/gziprequest.py", line 29, in write
	    if 'content-length' in self.request.headers:
	exceptions.AttributeError: Request instance has no attribute 'headers'
	
2017-07-27T11:41:51+0200 [twisted.python.log#info] 66.249.93.73 - - [27/Jul/2017:09:41:51 +0000] "GET / HTTP/1.1" 500 95 "-" "Mozilla/5.0 (Linux; Android 7.0;  Build/NRD90N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"

**Comment by Indjov** [comment]
@krdsx , do you downloaded that qweb from git?
If you didnt then try git clone that bug it`s fix in git.

**Comment by krdsx** [comment]
user@vps434405:~$ git clone https://github.com/qwebirc/qwebirc.git qwebircCloning into 'qwebirc'...
remote: Counting objects: 4723, done.
remote: Compressing objects: 100% (1986/1986), done.
remote: Total 4723 (delta 2898), reused 4486 (delta 2662), pack-reused 0
Receiving objects: 100% (4723/4723), 5.82 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (2898/2898), done.y
user@vps434405:~$ cd qwebirc/
user@vps434405:~/qwebirc$ git checkout stable
Branch stable set up to track remote branch stable from origin.
Switched to a new branch 'stable'
user@vps434405:~/qwebirc$ git pull
Already up-to-date.
user@vps434405:~/qwebirc$ ./compile.py
first run, checking dependencies...
0 errors, 0 warnings.
looks like you've got everything you need to run qwebirc!


and start but The same problem

**Comment by krdsx** [comment]
2017-07-27T19:47:29+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.6.0 (/usr/bin/python 2.7.13) starting up.
2017-07-27T19:47:29+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-07-27T19:47:29+0200 [-] RootSite starting on 9090
2017-07-27T19:47:29+0200 [qwebirc.root.RootSite#info] Starting factory <qwebirc.root.RootSite instance at 0x7f3e16f6e6c8>
2017-07-27T19:47:57+0200 [TimeoutHTTPChannel,0,66.249.93.69] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1752, in lineReceived
	    self.allContentReceived()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1845, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 766, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/home/user/qwebirc/qwebirc/engines/staticengine.py", line 33, in render
	    return static.File.render(self, request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 623, in render_GET
	    producer.start()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 702, in start
	    self.request.registerProducer(self, False)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 807, in registerProducer
	    self.channel.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2075, in registerProducer
	    return self.transport.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 233, in registerProducer
	    FileDescriptor.registerProducer(self, producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 112, in registerProducer
	    producer.resumeProducing()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 712, in resumeProducing
	    self.request.write(data)
	  File "/home/user/qwebirc/qwebirc/util/gziprequest.py", line 29, in write
	    if 'content-length' in self.request.headers:
	exceptions.AttributeError: Request instance has no attribute 'headers'
	
2017-07-27T19:47:57+0200 [twisted.python.log#info] 66.249.93.69 - - [27/Jul/2017:17:47:57 +0000] "GET / HTTP/1.1" 500 95 "-" "Mozilla/5.0 (Linux; Android 7.0; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"
2017-07-27T19:47:57+0200 [TimeoutHTTPChannel,0,66.249.93.69] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.RuntimeError: Producer was not unregistered for /
	
2017-07-27T19:47:57+0200 [TimeoutHTTPChannel,1,178.xxx.xx.xxx] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1752, in lineReceived
	    self.allContentReceived()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1845, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 766, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/home/user/qwebirc/qwebirc/engines/staticengine.py", line 33, in render
	    return static.File.render(self, request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 623, in render_GET
	    producer.start()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 702, in start
	    self.request.registerProducer(self, False)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 807, in registerProducer
	    self.channel.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 2075, in registerProducer
	    return self.transport.registerProducer(producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 233, in registerProducer
	    FileDescriptor.registerProducer(self, producer, streaming)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 112, in registerProducer
	    producer.resumeProducing()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 712, in resumeProducing
	    self.request.write(data)
	  File "/home/user/qwebirc/qwebirc/util/gziprequest.py", line 29, in write
	    if 'content-length' in self.request.headers:
	exceptions.AttributeError: Request instance has no attribute 'headers'
	
2017-07-27T19:47:57+0200 [twisted.python.log#info] 178.243.37.106 - - [27/Jul/2017:17:47:57 +0000] "GET / HTTP/1.1" 500 95 "-" "Mozilla/5.0 (Linux; Android 7.0; Lenovo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"
2017-07-27T19:47:57+0200 [TimeoutHTTPChannel,1,178.xxx.xx.xxx] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.RuntimeError: Producer was not unregistered for /

**Comment by krdsx** [comment]
Os debian 9

**Comment by retropc** [comment]
try master -- disabled gzip momentarily
