### ISSUE TITLE
run.py errors on Arch linux

### ISSUE THREAD

**Issue by Strykar** [qwebirc/qwebirc#369]
Everything works fine until I try to execute `run.py`:

```
$ python2 ./compile.py 
$ python2 ./run.py 
Unhandled Error
Traceback (most recent call last):
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/app.py", line 657, in run
    config.parseOptions()
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/app.py", line 624, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/usage.py", line 262, in parseOptions
    for (cmd, short, parser, doc) in self.subCommands:
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/app.py", line 641, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
--- <exception caught here> ---
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 217, in getPlugins
    adapted = interface(plugin, None)
  File "/home/strykar/.local/lib/python2.7/site-packages/zope/interface/interface.py", line 467, in _call_conform
    return conform(self)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 71, in __conform__
    return self.load()
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 66, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/reflect.py", line 301, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/reflect.py", line 240, in _importAndCheckStack
    return __import__(importName)
  File "/home/strykar/github/qwebirc/twisted/plugins/webirc.py", line 9, in <module>
    from twisted.application import internet, strports, service
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/strports.py", line 15, in <module>
    from twisted.internet import endpoints
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 58, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 157, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 140, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/lib/python2.7/site-packages/service_identity/__init__.py", line 7, in <module>
    from . import cryptography, pyopenssl
  File "/usr/lib/python2.7/site-packages/service_identity/cryptography.py", line 22, in <module>
    from ._common import (
  File "/usr/lib/python2.7/site-packages/service_identity/_common.py", line 290, in <module>
    class IPAddress_ID(object):
  File "/usr/lib/python2.7/site-packages/service_identity/_common.py", line 295, in IPAddress_ID
    ip = attr.ib(converter=ipaddress.ip_address)
exceptions.TypeError: attr() got an unexpected keyword argument 'converter'

Unhandled Error
Traceback (most recent call last):
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/app.py", line 659, in run
    print(config)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/usage.py", line 447, in __str__
    return self.getSynopsis() + '\n' + self.getUsage(width=None)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/usage.py", line 483, in getUsage
    for (cmd, short, parser, desc) in self.subCommands:
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/app.py", line 641, in subCommands
    for plug in sorted(plugins, key=attrgetter('tapname')):
--- <exception caught here> ---
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 217, in getPlugins
    adapted = interface(plugin, None)
  File "/home/strykar/.local/lib/python2.7/site-packages/zope/interface/interface.py", line 467, in _call_conform
    return conform(self)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 71, in __conform__
    return self.load()
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/plugin.py", line 66, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/reflect.py", line 301, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/python/reflect.py", line 240, in _importAndCheckStack
    return __import__(importName)
  File "/home/strykar/github/qwebirc/twisted/plugins/webirc.py", line 9, in <module>
    from twisted.application import internet, strports, service
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/application/strports.py", line 15, in <module>
    from twisted.internet import endpoints
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 58, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 157, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "/home/strykar/.local/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 140, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/lib/python2.7/site-packages/service_identity/__init__.py", line 7, in <module>
    from . import cryptography, pyopenssl
  File "/usr/lib/python2.7/site-packages/service_identity/cryptography.py", line 22, in <module>
    from ._common import (
  File "/usr/lib/python2.7/site-packages/service_identity/_common.py", line 290, in <module>
    class IPAddress_ID(object):
  File "/usr/lib/python2.7/site-packages/service_identity/_common.py", line 295, in IPAddress_ID
    ip = attr.ib(converter=ipaddress.ip_address)
exceptions.TypeError: attr() got an unexpected keyword argument 'converter'

Usage: twistd [options]
Options:
      --savestats      save the Stats object rather than the text output of the
                       profiler.
  -o, --no_save        do not save state on shutdown
  -e, --encrypted      The specified tap/aos file is encrypted.
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
      --originalname   Don't try to change the process name
      --syslog         Log to syslog, not to file
      --euid           Set only effective user-id rather than real user-id.
                       (This option has no effect unless the server is running
                       as root, in which case it means not to shed all
                       privileges after binding ports, retaining the option to
                       regain privileges in cases such as spawning processes.
                       Use with caution.)
  -l, --logfile=       log to a specified file, - for stdout
      --logger=        A fully-qualified name to a log observer factory to use
                       for the initial log observer.  Takes precedence over
                       --logfile and --syslog (when available).
  -p, --profile=       Run in profile mode, dumping results to specified file.
      --profiler=      Name of the profiler to use (profile, cprofile).
                       [default: cprofile]
  -f, --file=          read the given .tap file [default: twistd.tap]
  -y, --python=        read an application from within a Python file (implies
                       -o)
  -s, --source=        Read an application from a .tas file (AOT format).
  -d, --rundir=        Change to a supplied directory before running [default:
                       .]
      --prefix=        use the given prefix when syslogging [default: twisted]
      --pidfile=       Name of the pidfile [default: twistd.pid]
      --chroot=        Chroot to a supplied directory before running
  -u, --uid=           The uid to run as.
  -g, --gid=           The gid to run as.
      --umask=         The (octal) file creation mask to apply.
      --help-reactors  Display a list of possibly available reactor names.
      --version        Print version information and exit.
      --spew           Print an insanely verbose log of everything that happens.
                       Useful when debugging freezes or locks in complex code.
  -b, --debug          Run the application in the Python Debugger (implies
                       nodaemon),         sending SIGUSR2 will drop into
                       debugger
  -r, --reactor=       Which reactor to use (see --help-reactors for a list of
                       possibilities)
      --help           Display this help and exit.

twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    conch                A Conch SSH service.
    dns                  A domain name server.
    endpointforward      A simple stream endpoint forwarder
    ftp                  An FTP server.
    inetd                An inetd(8) replacement.
    mail                 An email service
    manhole              An interactive remote debugger service accessible via
                         telnet and ssh and providing syntax coloring and basic
                         line editing functionality.
    news                 A news server.
    portforward          A simple port-forwarder.
    procmon              A process watchdog / supervisor
    socks                A SOCKSv4 proxy service.
    web                  A general-purpose web server which can serve from a
                         filesystem or application resource.
    words                A modern words server
    xmpp-router          An XMPP Router server

./run.py: Unknown command: qwebirc
$
```

**Comment by MikkelDK** [comment]
Hi, @Strykar Do you have tried installed this? 

``pip install attrs==19.1.0`` - it should works =)

**Comment by retropc** [comment]
fixed in master
