### ISSUE TITLE
page refresh error

### ISSUE THREAD

**Issue by jmmizah** [qwebirc/qwebirc#386]
nick hangs after page refresh

I couldn't find the cause of the error, there was no problem before

Ping output timeout error after each output

qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://webchat.quakenet.org/dynamic/diamondus_epsilon/e/p?r=3bcc7211e6f820d54dacd4790a9d3af6&t=1': Synchronous XHR in page dismissal. See https://www.chromestatus.com/feature/4664843055398912 for more details.
    at Object.send (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:52223)
    at Object.extend._owner (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:12171)
    at Object.__send (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:98416)
    at Object.extend._owner (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:12171)
    at Object.send (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:96975)
    at Object.extend._owner (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:12171)
    at f (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:8141)
    at Object.send (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:8293)
    at Object.quit (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:138091)
    at Object.extend._owner (https://webchat.quakenet.org/static/diamondus1582418044/js/qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4:12171)
send @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
extend._owner @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
__send @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
extend._owner @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
send @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
extend._owner @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
f @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
(anonymous) @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
quit @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
extend._owner @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
(anonymous) @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
d @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4
o @ qui-b07dcc83065ba37c927fd5cd2eb7da9ef97c3b9c.js:4

**Comment by jmmizah** [comment]
@fishbot2000 @retropc  

Do you have any idea about this?

**Comment by jmmizah** [comment]
DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load
