### ISSUE TITLE
Getting installation error

### ISSUE THREAD

**Issue by legendskyk** [qwebirc/qwebirc#403]
installation give error what soluton for this:

Collecting Twisted==17.5.0
  Using cached Twisted-17.5.0.tar.bz2 (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/qwebirc/qwebirc/venv/bin/python2 -c 'import sys, setuptools,                                                tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rCAsqs/twisted/setup.py'"'"'; __f                                               ile__='"'"'/tmp/pip-install-rCAsqs/twisted/setup.py'"'"';f=getattr(tokenize, '"'                                               "'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"')                                               ;f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /t                                               mp/pip-pip-egg-info-6Rs1K6
         cwd: /tmp/pip-install-rCAsqs/twisted/
    Complete output (24 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Pl                                               ease upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will dr                                               op support for Python 2.7 in January 2021. More details about Python 2 support i                                               n pip can be found at https://pip.pypa.io/en/latest/development/release-process/                                               #python-2-support pip 21.0 will remove support for this functionality.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rCAsqs/twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/setupto                                               ols/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/setupto                                               ols/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/setupto                                               ols/dist.py", line 740, in finalize_options
        ep(self)
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/setupto                                               ols/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/pkg_res                                               ources/__init__.py", line 2324, in load
        return self.resolve()
      File "/home/qwebirc/qwebirc/venv/local/lib/python2.7/site-packages/pkg_res                                               ources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-install-rCAsqs/twisted/.eggs/incremental-22.10.0-py2.7.egg/                                               incremental/__init__.py", line 14, in <module>
        from typing import TYPE_CHECKING, Any, TypeVar, Union, Optional, Dict
    ImportError: No module named typing
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th                                               e logs for full command output.

**Comment by pwpreacher** [comment]
https://qwebirc.org/installation

did you do this from installations 

Create a virtual environment, activate it and install the python dependencies:
virtualenv -p python2 venv
source venv/bin/activate
pip install -r requirements.txt

as I found needed to do that to be able to get the correct requirements...

shalom

Preacher

**Comment by L4UR3NS** [comment]
I have exactly the same issue and did do it all from the installation manual on the website

```
root@vultr:~# cd qwebirc/
root@vultr:~/qwebirc# virtualenv -p python2 venv
created virtual environment CPython2.7.18.final.0-64 in 652ms
  creator CPython2Posix(dest=/root/qwebirc/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators NushellActivator,PythonActivator,FishActivator,CShellActivator,PowerShellActivator,BashActivator
root@vultr:~/qwebirc# source venv/bin/activate
(venv) root@vultr:~/qwebirc# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting autobahn==17.7.1
  Using cached autobahn-17.7.1-py2.py3-none-any.whl (278 kB)
Collecting simplejson==3.11.1
  Using cached simplejson-3.11.1.tar.gz (78 kB)
Collecting Twisted==17.5.0
  Using cached Twisted-17.5.0.tar.bz2 (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /root/qwebirc/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-GmzQVb/twisted/setup.py'"'"'; __file__='"'"'/tmp/pip-install-GmzQVb/twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Rj6LA2
         cwd: /tmp/pip-install-GmzQVb/twisted/
    Complete output (24 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GmzQVb/twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/root/qwebirc/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/root/qwebirc/venv/lib/python2.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/root/qwebirc/venv/lib/python2.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep(self)
      File "/root/qwebirc/venv/lib/python2.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/root/qwebirc/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/root/qwebirc/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-install-GmzQVb/twisted/.eggs/incremental-22.10.0-py2.7.egg/incremental/__init__.py", line 14, in <module>
        from typing import TYPE_CHECKING, Any, TypeVar, Union, Optional, Dict
    ImportError: No module named typing
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) root@vultr:~/qwebirc#

```

**Comment by L4UR3NS** [comment]
Just resolved my error. In case anyone needs this in the future, it was as simple as

`pip install typing`

However before that I also up/downgraded pip itself and removed the venv
